name: "InfluxDB 3 MCP Server"
description: " MCP Server for InfluxDB 3"
version: "1.0.1"
slug: "influxdb3-mcp-server"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  instance_url: "http://a0d7b954-influxdb:8086"
  token: null
  product_type: "core"